services:
  mongodb:
    image: mongo:6.0
    container_name: cloud_computing
    ports:
      - "28017:27017" # as to avoid collision if the user has a mongo setup
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
